name: Release LADirectus2QGIS

on:
  push:
    tags:
      - 'v*'       # Triggers on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Package plugin
      run: |
        python packageLADirectus2QGIS.py

    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: 'LADirectus2QGIS_*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}